#ifndef MICROSTRAIN_PLATFORM_H
#define MICROSTRAIN_PLATFORM_H

#if defined _WIN32
#ifndef MICROSTRAIN_PLATFORM_WINDOWS
#define MICROSTRAIN_PLATFORM_WINDOWS
#endif // MICROSTRAIN_PLATFORM_WINDOWS
#if defined _MSC_VER
#ifndef MICROSTRAIN_PLATFORM_MSVC
#define MICROSTRAIN_PLATFORM_MSVC
#endif // MICROSTRAIN_PLATFORM_MSVC
#elif defined __MINGW32__
#ifndef MICROSTRAIN_PLATFORM_MINGW
#define MICROSTRAIN_PLATFORM_MINGW
#endif // MICROSTRAIN_PLATFORM_MINGW
#endif // _MSC_VER
#elif defined __APPLE__
#ifndef MICROSTRAIN_PLATFORM_APPLE
#define MICROSTRAIN_PLATFORM_APPLE
#endif // MICROSTRAIN_PLATFORM_APPLE
#elif defined __linux__ && !defined __ANDROID__
#ifndef MICROSTRAIN_PLATFORM_LINUX
#define MICROSTRAIN_PLATFORM_LINUX
#endif // MICROSTRAIN_PLATFORM_LINUX
#else // Unknown
#error Unknown platform
#endif // _WIN32

#if defined MICROSTRAIN_PLATFORM_LINUX || defined MICROSTRAIN_PLATFORM_APPLE
#ifndef MICROSTRAIN_PLATFORM_UNIX
#define MICROSTRAIN_PLATFORM_UNIX
#endif //MICROSTRAIN_PLATFORM_UNIX
#endif // MICROSTRAIN_PLATFORM_LINUX || MICROSTRAIN_PLATFORM_APPLE

#define MICROSTRAIN_PLATFORM_DESKTOP

#endif // MICROSTRAIN_PLATFORM_H
