#pragma once

enum {
    MIP_INDEX_SYNC1 = 0,
    MIP_INDEX_SYNC2,
    MIP_INDEX_DESCSET,
    MIP_INDEX_LENGTH,
    MIP_INDEX_PAYLOAD,
};

enum {
    MIP_INDEX_FIELD_LEN = 0,
    MIP_INDEX_FIELD_DESC,
    MIP_INDEX_FIELD_PAYLOAD,
};

#define MIP_HEADER_LENGTH      4
#define MIP_CHECKSUM_LENGTH    2
#define MIP_PAYLOAD_LENGTH_MIN 0
#define MIP_PAYLOAD_LENGTH_MAX 255
#define MIP_PACKET_LENGTH_MIN  (MIP_HEADER_LENGTH + MIP_CHECKSUM_LENGTH + MIP_PAYLOAD_LENGTH_MIN)
#define MIP_PACKET_LENGTH_MAX  (MIP_HEADER_LENGTH + MIP_CHECKSUM_LENGTH + MIP_PAYLOAD_LENGTH_MAX)

#define MIP_FIELD_HEADER_LENGTH MIP_INDEX_FIELD_PAYLOAD
#define MIP_FIELD_LENGTH_MAX    255
#define MIP_FIELD_PAYLOAD_LENGTH_MAX (MIP_FIELD_LENGTH_MAX - MIP_FIELD_HEADER_LENGTH)

#define MIP_SYNC1 0x75
#define MIP_SYNC2 0x65
